name: delivery_backoffice_dw10
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  awesome_snackbar_content: ^0.1.4
  brasil_fields: ^1.15.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_mobx: ^2.2.1
  flutter_modular: ^6.3.4
  flutter_web_plugins:
    sdk: flutter
  loading_animation_widget: ^1.3.0
  mobx: ^2.4.0
  url_strategy: ^0.3.0
  validatorless: ^1.2.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUS1p-ExtraBold.ttf
          weight: 800
